import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  Printer, 
  Sparkles, 
  Shield, 
  TrendingUp, 
  Cpu, 
  Globe, 
  AlertTriangle, 
  HelpCircle, 
  Layers, 
  BookOpen, 
  CheckCircle2,
  GitBranch,
  ShieldCheck,
  Zap,
  Lightbulb,
  Maximize2,
  Minimize2,
  ChevronDown,
  ChevronUp,
  Activity
} from 'lucide-react';
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend
} from 'recharts';
import { WorldState, SimulationConfig } from '../../shared/types.ts';
import { explainSimplyLocal, toConversationalHinglish } from '../../shared/hinglishHelper.ts';
import { CoverArtGenerator } from './CoverArtGenerator.tsx';
import { generateCoverArtSVG } from '../utils/coverArtRenderer.ts';

interface WorldReportViewProps {
  worldState: WorldState;
  config: SimulationConfig;
}

export const WorldReportView: React.FC<WorldReportViewProps> = ({ worldState, config }) => {
  // Simple Mode is Default
  const [reportMode, setReportMode] = useState<'simple' | 'detailed'>('simple');
  const [copied, setCopied] = useState<boolean>(false);
  const [expandedSectionIds, setExpandedSectionIds] = useState<Record<string, boolean>>({});
  const [showCoverModal, setShowCoverModal] = useState<boolean>(false);

  const isHinglish = config.communicationStyle === 'hinglish' || !config.communicationStyle;

  // Prepare chart data from timeline events
  const chartData = (worldState.timeline || []).map((t, idx) => ({
    year: t.year,
    name: `${t.year} AD`,
    title: t.title,
    economicStability: typeof t.economicStability === 'number' ? t.economicStability : Math.min(95, Math.max(30, 60 + Math.sin(idx * 1.5) * 20)),
    societalHarmony: typeof t.societalHarmony === 'number' ? t.societalHarmony : Math.min(95, Math.max(30, 65 + Math.cos(idx * 1.2) * 18)),
    confidence: t.confidence || 85
  }));

  const toggleSectionExplain = (id: string) => {
    setExpandedSectionIds(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const generateMarkdownReport = (): string => {
    const parsed = worldState.parsedScenario;
    return `# INTELLIGENCE DOSSIER: ${worldState.finalWorldName.toUpperCase()}
Generated by Chronos Multi-Agent Alternate Reality Engine
Scenario: "${config.scenarioTitle}" (${config.startingYear} - ${config.endYear})
Synthesis Confidence: ${worldState.synthesisConfidence}%

---

## 1. SIMPLE EXECUTIVE OVERVIEW
- **Kya Change Hua**: ${worldState.divergencePoint.event} (${worldState.divergencePoint.year} AD)
- **Iska Sabse Bada Effect**: ${worldState.scenarioSummary}
- **Kaun Powerful Bana**: ${worldState.countries.slice(0, 3).map(c => `${c.name} (Power: ${c.economicStrength}/100)`).join(', ')}
- **Sabse Uncertain Part**: ${worldState.uncertaintiesAndCaveats.join('; ')}

---

## 2. DETAILED SYNTHESIS
${worldState.executiveSummary}

## 3. GEOPOLITICAL BLOCS & ALLIANCES
${worldState.alliances.map(a => `### ${a.name}
- **Leader**: ${a.leaderCountryId}
- **Members**: ${a.memberCountryIds.join(', ')}
- **Ideology**: ${a.ideology}
- **Strategic Doctrine**: ${a.description}
`).join('\n')}

## 4. MAJOR SOVEREIGN FACTIONS
${worldState.countries.map(c => `### ${c.name} (${c.id})
- **Government**: ${c.government} | Ideology: ${c.ideology}
- **Capital**: ${c.capital} | Population: ${c.populationEstimate}
- **Power Ratings**: Economy: ${c.economicStrength}/100 | Military: ${c.militaryStrength}/100 | Tech: ${c.technologyLevel}/100
- **Status Notes**: ${c.statusNotes}
`).join('\n')}

## 5. ALTERNATIVE TECHNOLOGICAL MATRIX
- **Advanced Ahead of History**: ${worldState.technologyState.advancedAheadOfHistory.join('; ')}
- **Delayed or Never Invented**: ${worldState.technologyState.delayedOrNeverInvented.join('; ')}
- **Alternative Tech Paths**: ${worldState.technologyState.alternativeTechnologicalPaths.join('; ')}

## 6. AGENT CONSENSUS & UNRESOLVED DISPUTES
- **High Consensus**: ${worldState.agentAgreementBreakdown.highConsensusAreas.join('; ')}
- **Disputed Topics**: ${worldState.agentAgreementBreakdown.disputedTopics.map(d => `${d.topic} (Majority: ${d.majorityView})`).join('; ')}
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(worldState, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `chronos-world-${config.scenarioTitle.toLowerCase().replace(/[^a-z0-9]/g, '-')}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const parsed = worldState.parsedScenario;

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 sm:px-8 space-y-8">
      {/* Header & Export Toolbar */}
      <div className="bg-[#121417] border border-[#2A2D32] rounded-xl p-6 sm:p-8 shadow-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-6">
        <div>
          <span className="text-[10px] uppercase tracking-widest-plus text-[#C5A059] mb-2 block font-medium">
            Final World Dossier Synthesis • {config.startingYear} to {config.endYear} AD
          </span>
          <h2 className="text-3xl sm:text-4xl font-serif italic text-white">
            {worldState.finalWorldName}
          </h2>
          <p className="text-xs text-[#8E8B82] mt-1.5 font-mono">
            Synthesis Confidence: <span className="text-[#52B788] font-bold">{worldState.synthesisConfidence}%</span> • Multi-Agent Disciplinary Consensus
          </p>
        </div>

        {/* Mode Toggle & Export Buttons */}
        <div className="flex flex-wrap items-center gap-2.5">
          {/* Simple vs Detailed Toggle */}
          <div className="bg-[#0D0E10] border border-[#2A2D32] rounded-lg p-0.5 flex items-center mr-2">
            <button
              onClick={() => setReportMode('simple')}
              className={`px-3 py-1.5 rounded-md text-xs font-mono font-bold transition-all cursor-pointer ${
                reportMode === 'simple'
                  ? 'bg-[#C5A059] text-black shadow-sm'
                  : 'text-[#8E8B82] hover:text-white'
              }`}
            >
              Simple Mode (Default)
            </button>
            <button
              onClick={() => setReportMode('detailed')}
              className={`px-3 py-1.5 rounded-md text-xs font-mono font-bold transition-all cursor-pointer ${
                reportMode === 'detailed'
                  ? 'bg-[#C5A059] text-black shadow-sm'
                  : 'text-[#8E8B82] hover:text-white'
              }`}
            >
              Detailed Academic
            </button>
          </div>

          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#0D0E10] border border-[#2A2D32] text-xs font-mono text-[#D8D5CD] hover:text-white hover:border-[#C5A059] transition-all cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-[#C5A059]" />}
            <span>{copied ? 'Copied' : 'Copy'}</span>
          </button>
          <button
            onClick={handleDownloadJSON}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#0D0E10] border border-[#2A2D32] text-xs font-mono text-[#D8D5CD] hover:text-white hover:border-[#C5A059] transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-[#C5A059]" />
            <span>JSON</span>
          </button>
        </div>
      </div>

      {/* ───────────────────────────────────────────────────────────── */}
      {/* HISTORICAL STABILITY & HARMONY TRAJECTORY (RECHARTS)         */}
      {/* ───────────────────────────────────────────────────────────── */}
      {chartData.length > 0 && (
        <div className="bg-[#121417] border border-[#2A2D32] rounded-2xl p-6 shadow-2xl space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-[#22252A] pb-3">
            <div>
              <div className="flex items-center gap-2">
                <Activity className="w-4 h-4 text-[#C5A059]" />
                <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                  Civilizational Trajectory & Metric Calibration
                </h3>
              </div>
              <p className="text-xs text-[#8E8B82] mt-0.5">
                Dynamic projection of Economic Stability vs Societal Harmony across the divergence span ({config.startingYear}–{config.endYear} AD)
              </p>
            </div>

            <div className="flex items-center gap-4 text-xs font-mono">
              <span className="flex items-center gap-1.5 text-[#52B788]">
                <span className="w-2.5 h-2.5 rounded-full bg-[#52B788]" /> Economic Stability
              </span>
              <span className="flex items-center gap-1.5 text-[#6BA4B8]">
                <span className="w-2.5 h-2.5 rounded-full bg-[#6BA4B8]" /> Societal Harmony
              </span>
            </div>
          </div>

          <div className="h-64 w-full pt-2">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData} margin={{ top: 10, right: 20, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="econGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#52B788" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="#52B788" stopOpacity={0.0}/>
                  </linearGradient>
                  <linearGradient id="harmGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6BA4B8" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="#6BA4B8" stopOpacity={0.0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#22252A" vertical={false} />
                <XAxis 
                  dataKey="year" 
                  stroke="#6B7280" 
                  fontSize={11} 
                  tickLine={false}
                  tickFormatter={(v) => `${v} AD`}
                />
                <YAxis 
                  stroke="#6B7280" 
                  fontSize={11} 
                  domain={[0, 100]} 
                  tickLine={false}
                  tickFormatter={(v) => `${v}%`}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: '#15181E', 
                    borderColor: '#2A2D32', 
                    borderRadius: '8px', 
                    color: '#FFF',
                    fontSize: '12px'
                  }}
                  itemStyle={{ fontSize: '11px' }}
                  labelFormatter={(label) => `Timeline Event: ${label} AD`}
                />
                <Area 
                  type="monotone" 
                  dataKey="economicStability" 
                  name="Economic Stability"
                  stroke="#52B788" 
                  strokeWidth={2}
                  fillOpacity={1} 
                  fill="url(#econGradient)" 
                />
                <Area 
                  type="monotone" 
                  dataKey="societalHarmony" 
                  name="Societal Harmony"
                  stroke="#6BA4B8" 
                  strokeWidth={2}
                  fillOpacity={1} 
                  fill="url(#harmGradient)" 
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}

      {/* ───────────────────────────────────────────────────────────── */}
      {/* CONCEPTUAL WORLD MAP COVER ART & ATLAS THUMBNAIL              */}
      {/* ───────────────────────────────────────────────────────────── */}
      <div className="bg-[#121417] border border-[#C5A059]/40 rounded-2xl overflow-hidden shadow-2xl p-5 sm:p-6 grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
        {/* Left Thumbnail Aspect Frame */}
        <div className="md:col-span-5 relative rounded-xl overflow-hidden border border-[#C5A059]/50 aspect-video bg-black shadow-xl group">
          {worldState.coverArtUrl ? (
            <img 
              src={worldState.coverArtUrl} 
              alt={`${worldState.finalWorldName} Cover Art`}
              referrerPolicy="no-referrer"
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
            />
          ) : (
            <div 
              className="w-full h-full"
              dangerouslySetInnerHTML={{ 
                __html: generateCoverArtSVG({
                  scenarioTitle: worldState.finalWorldName || config.scenarioTitle,
                  scenarioDescription: worldState.scenarioSummary || config.scenarioDescription,
                  startingYear: config.startingYear,
                  endYear: config.endYear,
                  style: (worldState.coverArtStyle as any) || 'imperial_gold'
                }) 
              }}
            />
          )}

          <div className="absolute top-2.5 right-2.5 bg-black/80 backdrop-blur-md px-2 py-1 rounded text-[9px] font-mono text-[#C5A059] border border-[#C5A059]/40">
            Atlas Master
          </div>
        </div>

        {/* Right Info & Actions */}
        <div className="md:col-span-7 space-y-3">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded bg-[#C5A059]/20 border border-[#C5A059]/40 text-[#C5A059] text-[9px] font-mono uppercase tracking-widest font-bold flex items-center gap-1.5">
              <Sparkles className="w-3 h-3" /> Official Intelligence Dossier Cover
            </span>
          </div>

          <h3 className="text-xl sm:text-2xl font-serif italic text-white font-bold">
            {worldState.finalWorldName} • Speculative World Atlas
          </h3>

          <p className="text-xs text-[#A8A59D] font-mono leading-relaxed">
            {worldState.coverArtPrompt || `High-contrast speculative cartography capturing the geopolitical divergence starting in ${worldState.divergencePoint?.year || config.startingYear || 1888} AD across ${config.geographicScope || 'global'} theaters.`}
          </p>

          <div className="flex flex-wrap items-center gap-3 pt-2">
            <button
              onClick={() => setShowCoverModal(true)}
              className="px-4 py-2.5 bg-[#C5A059] hover:bg-[#D4AF37] text-black font-semibold rounded-lg text-xs uppercase tracking-wider transition-all flex items-center gap-2 shadow-md cursor-pointer"
            >
              <Sparkles className="w-3.5 h-3.5 fill-black" />
              <span>🎨 Open Cover Art Studio & Download 4K</span>
            </button>
          </div>
        </div>
      </div>

      {/* ───────────────────────────────────────────────────────────── */}
      {/* 1. SIMPLE DISPLAY MODE (DEFAULT)                              */}
      {/* ───────────────────────────────────────────────────────────── */}
      {reportMode === 'simple' && (
        <div className="space-y-6">
          {/* 4 Core Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* 1. Kya Change Hua? */}
            <div className="p-5 rounded-xl bg-[#15171A] border border-[#C5A059]/40 shadow-xl space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold uppercase tracking-wider text-[#C5A059] flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4" /> KYA CHANGE HUA? (Key Turning Point)
                </span>
                <span className="text-[10px] font-mono text-[#8E8B82]">{worldState.divergencePoint?.year || config.startingYear || 1888} AD</span>
              </div>
              <h4 className="text-base font-bold text-white">
                {worldState.divergencePoint?.event || config.scenarioTitle}
              </h4>
              <p className="text-xs text-[#D8D5CD] leading-relaxed">
                {worldState.divergencePoint?.mechanism || 'Ek critical event badla, jisse aage ka poora itihaas naye raaste par chala gaya.'}
              </p>
            </div>

            {/* 2. Iska Sabse Bada Effect? */}
            <div className="p-5 rounded-xl bg-[#15171A] border border-[#52B788]/40 shadow-xl space-y-2">
              <span className="text-xs font-mono font-bold uppercase tracking-wider text-[#52B788] flex items-center gap-1.5">
                <Globe className="w-4 h-4" /> ISKA SABSE BADA EFFECT? (World Impact)
              </span>
              <p className="text-xs sm:text-sm text-white leading-relaxed font-medium">
                {worldState.scenarioSummary}
              </p>
              <p className="text-[11px] text-[#8E8B82] leading-relaxed">
                Naye trade networks aur power structures ban gaye jisse pure world ki daily life aur politics reshape hui.
              </p>
            </div>

            {/* 3. Kaun Powerful Bana? */}
            <div className="p-5 rounded-xl bg-[#15171A] border border-blue-500/40 shadow-xl space-y-3">
              <span className="text-xs font-mono font-bold uppercase tracking-wider text-blue-400 flex items-center gap-1.5">
                <Shield className="w-4 h-4" /> KAUN POWERFUL BANA? (Top Powers)
              </span>
              <div className="space-y-2">
                {(worldState.countries || []).slice(0, 3).map((c, i) => (
                  <div key={c.id || i} className="p-2 rounded-lg bg-[#0D0E10] border border-[#2A2D32] flex items-center justify-between text-xs">
                    <div>
                      <span className="font-bold text-white">{i + 1}. {c.name}</span>
                      <span className="text-[10px] text-[#8E8B82] block">{c.government}</span>
                    </div>
                    <span className="font-mono text-[#52B788] font-bold">Power: {c.economicStrength}/100</span>
                  </div>
                ))}
              </div>
            </div>

            {/* 4. Sabse Uncertain Part? */}
            <div className="p-5 rounded-xl bg-[#15171A] border border-amber-500/40 shadow-xl space-y-2">
              <span className="text-xs font-mono font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4" /> SABSE UNCERTAIN PART? (Fragilities)
              </span>
              <ul className="space-y-1.5 text-xs text-[#D8D5CD]">
                {(worldState.uncertaintiesAndCaveats || []).slice(0, 3).map((u, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <span className="text-amber-400">•</span>
                    <span>{u}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Simple Technology Evolution Summary */}
          <div className="p-6 rounded-xl bg-[#15171A] border border-[#2A2D32] shadow-xl space-y-4">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-purple-400 flex items-center gap-1.5">
              <Cpu className="w-4 h-4" /> TECHNOLOGY KA KYA HUA? (Scientific Tree)
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
              <div className="p-3 rounded-lg bg-[#0D0E10] border border-[#2A2D32]">
                <span className="text-[10px] font-mono text-emerald-400 font-bold block mb-1">Time Se Pehle Invent Hua:</span>
                <p className="text-white">{(worldState.technologyState?.advancedAheadOfHistory || []).slice(0, 2).join(', ') || 'Alternative energy & mechanics'}</p>
              </div>
              <div className="p-3 rounded-lg bg-[#0D0E10] border border-[#2A2D32]">
                <span className="text-[10px] font-mono text-rose-400 font-bold block mb-1">Delay Ya Kabhi Nahi Bana:</span>
                <p className="text-white">{(worldState.technologyState?.delayedOrNeverInvented || []).slice(0, 2).join(', ') || 'Traditional fossil engines'}</p>
              </div>
              <div className="p-3 rounded-lg bg-[#0D0E10] border border-[#2A2D32]">
                <span className="text-[10px] font-mono text-[#C5A059] font-bold block mb-1">Naya Scientific Path:</span>
                <p className="text-white">{(worldState.technologyState?.alternativeTechnologicalPaths || []).slice(0, 2).join(', ') || 'Hydrothermal grids & bio-optics'}</p>
              </div>
            </div>
          </div>

          {/* Expert Consensus Summary in Easy Hinglish */}
          <div className="p-6 rounded-xl bg-[#15171A] border border-[#2A2D32] shadow-xl space-y-3">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-[#C5A059] flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" /> EXPERTS KIS BAAT PAR AGREE HUE?
            </span>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-[#D8D5CD]">
              <div className="p-3.5 rounded-lg bg-[#0D0E10] border border-emerald-500/20 space-y-1">
                <span className="text-[10px] font-mono text-emerald-400 font-bold block">Pakki Sahmati (Consensus):</span>
                {(worldState.agentAgreementBreakdown?.highConsensusAreas || []).slice(0, 2).map((a, i) => (
                  <p key={i}>✓ {a}</p>
                ))}
              </div>
              <div className="p-3.5 rounded-lg bg-[#0D0E10] border border-rose-500/20 space-y-1">
                <span className="text-[10px] font-mono text-rose-400 font-bold block">Debate Ka Mudda (Disputed):</span>
                {(worldState.agentAgreementBreakdown?.disputedTopics || []).slice(0, 1).map((d, i) => (
                  <p key={i}>⚔ {d.topic}: Majority maanti hai "{(d.majorityView || '').slice(0, 80)}..."</p>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ───────────────────────────────────────────────────────────── */}
      {/* 2. DETAILED ACADEMIC DISPLAY MODE                             */}
      {/* ───────────────────────────────────────────────────────────── */}
      {reportMode === 'detailed' && (
        <div className="space-y-6">
          {/* Executive Summary */}
          <div className="p-6 rounded-xl bg-[#15171A] border border-[#2A2D32] shadow-xl space-y-3">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-[#C5A059] block">
              1. Executive Academic Synthesis
            </span>
            <p className="text-xs sm:text-sm text-[#D8D5CD] leading-relaxed whitespace-pre-line">
              {worldState.executiveSummary}
            </p>
          </div>

          {/* Sovereign Factions Detailed Table */}
          <div className="p-6 rounded-xl bg-[#15171A] border border-[#2A2D32] shadow-xl space-y-4">
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-white block">
              2. Sovereign Jurisdictions & Power Ratings
            </span>
            <div className="space-y-3">
              {(worldState.countries || []).map(c => (
                <div key={c.id} className="p-4 rounded-lg bg-[#0D0E10] border border-[#2A2D32] space-y-2 text-xs">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-bold text-white">{c.name} ({c.id})</span>
                    <span className="text-xs font-mono text-[#C5A059]">Cap: {c.capital} • Pop: {c.populationEstimate}</span>
                  </div>
                  <div className="flex gap-4 font-mono text-[11px] text-[#8E8B82]">
                    <span>Economy: <strong className="text-[#52B788]">{c.economicStrength}/100</strong></span>
                    <span>Military: <strong className="text-blue-400">{c.militaryStrength}/100</strong></span>
                    <span>Tech: <strong className="text-purple-400">{c.technologyLevel}/100</strong></span>
                  </div>
                  <p className="text-[#D8D5CD] text-xs leading-relaxed">{c.statusNotes}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Cover Art Studio Modal */}
      {showCoverModal && (
        <CoverArtGenerator
          isModal={true}
          scenarioTitle={worldState.finalWorldName || config.scenarioTitle}
          scenarioDescription={worldState.scenarioSummary || config.scenarioDescription}
          startingYear={config.startingYear}
          endYear={config.endYear}
          geographicScope={config.geographicScope}
          initialStyle={worldState.coverArtStyle || 'imperial_gold'}
          onApplyCoverArt={(url, style, prompt) => {
            worldState.coverArtUrl = url;
            worldState.coverArtStyle = style;
            worldState.coverArtPrompt = prompt;
          }}
          onClose={() => setShowCoverModal(false)}
        />
      )}
    </div>
  );
};
